[build]
  command = "npm install"
  functions = "functions/"

# すべてのリクエストを、私たちの作った賢いサーバープログラムに転送する
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200


5.  貼り付けたら、緑色の「Commit changes...」ボタンを押して保存します。

---

